import Header from '@/components/Layout/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './provider';
import Notify from '@/components/Layout/Notify';
import GlobalCall from '@/components/Layout/GlobalCall';
import Auth from '@/components/Layout/Auth';
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  pathName,
  children,
}: Readonly<{
  children: React.ReactNode;
  pathName: any;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className="bg-slate-100">
          <GlobalCall />
          <Header />
          <div className="px-24 pb-4">
            <Auth>{children}</Auth>
          </div>
          <Notify />
        </body>
      </Providers>
    </html>
  );
}
