import Auth from '@/components/Layout/Auth';
import GlobalCall from '@/components/Layout/GlobalCall';
import Header from '@/components/Layout/Header';
import Notify from '@/components/Layout/Notify';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './provider';
import Body from '@/components/Layout/Body';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <Body>
          <GlobalCall />
          <Header />
          <div className="px-4 2xl:px-24 py-4">
            <Auth>{children}</Auth>
          </div>
          <Notify />
        </Body>
      </Providers>
    </html>
  );
}
